server:
  port: ${PORT:8086}
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Akshaypandey2003/Travo-microservices-configuration
          clone-on-start: true