server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: Users
  config:
    import: optional:configserver:http://localhost:8086

logging:
  level:
    org.springframework.kafka: DEBUG


resilience4j:

  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s

    instances:
      notificationServiceCircuitBreaker:
        baseConfig: default
      

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 2s
    instances:
      notificationServiceRetry:
        baseConfig: default

user:
  pagination:
    max-page-size: 100
  notifications:
    retry:
      fixed-delay-ms: 30000
      batch-size: 50
      max-attempts: 10