server:
  port: 8088

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Users
  application:
    name: USER-SERVICE
  security:
    user:
      name: admin
      password: password
  config:
    import: configserver:http://localhost:8086

# File size limit for multipart requests
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Okta Configuration
okta:
  oauth2:
    issuer: https://dev-95846997.okta.com/oauth2/default
    audience: api://default
