server:
  port: ${PORT:8080}

spring:
  application:
    name: user-service
  data:
    mongodb:
      database: Users
  config:
    import: optional:configserver:http://localhost:8086

logging:
  level:
    org.springframework.kafka: DEBUG


