server:
  port: 8085

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  cloud:
    gateway:
      routes:
      - id: HOTEL-INFO
        uri: lb://HOTEL-INFO
        predicates:
        - Path=/hotelInfo/**

      - id: HOTEL-SERVICE
        uri: lb://HOTEL-SERVICE
        predicates:
        - Path=/hotel/**

      - id: REVIEW-SERVICE
        uri: lb://REVIEW-SERVICE
        predicates:
        - Path=/review/**

      - id: ROOM-SERVICE
        uri: lb://ROOM-SERVICE
        predicates:
        - Path=/rooms/**

      - id: BOOKING-SERVICE
        uri: lb://BOOKING-SERVICE
        predicates:
        - Path=/booking/**

      - id: USER-SERVICE-SECURED
        uri: lb://USER-SERVICE
        predicates:
        - Path=/user/**

      - id: USER-SERVICE-PUBLIC
        uri: lb://USER-SERVICE
        predicates:
        - Path=/auth/**
        
      
      - id: TRIPS-SERVICE
        uri: lb://TRIPS-SERVICE
        predicates:
        - Path=/trip/**

      - id: FEEDBACK-SERVICE
        uri: lb://FEEDBACK-SERVICE
        predicates:
        - Path=/feedback/**

      - id: CHATS-SERVICE
        uri: lb://CHATS-SERVICE
        predicates:
        - Path=/chat/**, /chat/message/**

      - id: BLOGS-SERVICE
        uri: lb://BLOGS-SERVICE
        predicates:
        - Path=/blog/**

      - id: BLOGS-COMMENT-SERVICE
        uri: lb://BLOGS-COMMENT-SERVICE
        predicates:
        - Path=/comment/**

      - id: USER-WEBSOCKET-ROUTE
        uri: lb://USER-SERVICE
        predicates:
            - Path=/ws/**

        # filters:
        #     - name: RewritePath
        #       args:
        #         regexp: /ws/(?<segment>.*)
        #         replacement: /${segment}
      
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  
  application:
    name: API-GATEWAY
  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:8086}


logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG


jwt:
  secret: ${JWT_SECRET:my-super-secret-jwt-key-my-super-secret-jwt-key}
  expiration: ${JWT_EXPIRATION:3600000}


        