# BlogCommentsService - application-docker.yaml
server:
  port: ${SERVER_PORT:8091}

spring:
  application:
    name: BLOGS-COMMENT-SERVICE

  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/BlogComments}
      database: BlogComments

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:8086}

  cloud:
    config:
      failFast: false
      retry:
        maxAttempts: 6
        initialInterval: 2000
        multiplier: 1.5



  security:
   user:
     name: ${APP_BASIC_AUTH_USER:admin}
     password: ${APP_BASIC_AUTH_PASSWORD:password}

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
