server:
  port: 8091

spring:
  data:
    mongodb:
      database: BlogComments
  application:
    name: BLOGS-COMMENT-SERVICE

  config:
    import: ${SPRING_CONFIG_IMPORT:optional:configserver:http://config-server:8086}

