server:
  port: ${PORT:8095}

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8086

logging:
  level:
    org.springframework.kafka: DEBUG
