server:
  port: 8090

spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: Trips
  application:
    name: TRIPS-SERVICE
  security:
    user:
      name: admin
      password: password


  config:
    import: configserver:http://localhost:8086

# File size limit for multipart requests
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB